---
title: "SEMANA-13-SISTEMATIZACION"
author: "ALEXANDRA_VIVAS_RAMOS"
format: html
editor: visual
---

```{r}
data<- read_csv("C:/Users/USUARIO/Downloads/s13_hemodialisis.csv") 
```

```{r}
#VER LAS 6 PRIMERAS FILAS DE LA DATA 
head(data) 
```

```{r}
#ESTRUCTURA DE LA DATA
str(data)
```

```{r}
#MEDIDAS DE TENDENCIA CENTRAL 
#MEDIA ARITMETICA
mean(data$Edad)
```

```{r}
#MEDIANA
median(data$Edad)
```

```{r}
#MODA
mode_Edad<-names(sort(table(data$Edad),decreasing = TRUE))
```

```{r}
#MEDIDAD DE DISPERCION
var(data$Edad,na.rm = TRUE)
```

```{r}
#DESVIACION ESTANDAR
sd(data$Edad,na.rm = TRUE)
```

```{r}
#RANGO
range(data$Edad,na.rm = TRUE)
```

```{r}
#RANGO INTERCUARTILICO
IQR(data$Edad,na.rm = TRUE)
```

```{r}
#MEDIDAS DE POSICION
quantile(data$Edad,probs =c(0.25,0.50,0.75,0.90),na.rm = TRUE)
summary(data$Edad)
```

```{r}
#RESUMEN DE TODAS LAS VARIABLES
summary(data)
```

```{r}
#TABLA DE FRECUENCIAS
table(data$Sexo)
prop.table(table(data$Edad))
```

```{r}
#VISUALIZACIONES GRAFICAS
#HISTOGRAMA
ggplot(data, aes(x= IMC))+geom_histogram(bing = 30)+theme_minimal()
```

